name: teste
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
