name: teste
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2

dev_dependencies:
  intl_utils: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.jpg"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/mobilelogin.png
    - lib/l10n/
