name: teste
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  extended_masked_text: ^3.0.1
  provider: ^6.1.2

dev_dependencies:
  intl_utils: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.jpg"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/mobilelogin.png
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_pt.arb

l10n:
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-localization-file: app_localizations.dart